@php($editing = $mockTest->exists)
<x-layouts.admin :title="$editing ? 'Edit Mock Test' : 'Create Mock Test'">
    <form method="POST" action="{{ $editing ? route('admin.mock-tests.update', $mockTest) : route('admin.mock-tests.store') }}" x-data="{ type: @js(old('type', $mockTest->type)) }" class="mx-auto max-w-4xl space-y-6">
        @csrf @if($editing) @method('PUT') @endif
        @if($errors->any())<div class="rounded-lg border border-red-200 bg-red-50 p-4 text-red-700">{{ $errors->first() }}</div>@endif
        <section class="rounded-lg border bg-white p-6 shadow-sm"><div class="grid gap-5 sm:grid-cols-2"><div><label class="block text-sm font-bold">Name</label><input name="name" value="{{ old('name', $mockTest->name) }}" required class="mt-1 w-full rounded-md border-gray-300"></div><div><label class="block text-sm font-bold">Type</label><select name="type" x-model="type" class="mt-1 w-full rounded-md border-gray-300"><option value="theory">Theory test (English only)</option><option value="hazard">Hazard perception</option></select></div><div class="sm:col-span-2"><label class="block text-sm font-bold">Place under subsection</label><select name="sub_section_id" required class="mt-1 w-full rounded-md border-gray-300"><option value="">Select placement</option>@foreach($subSections as $sub)<option value="{{ $sub->id }}" @selected((string)old('sub_section_id', $mockTest->sub_section_id)===(string)$sub->id)>{{ $sub->section->name }} / {{ $sub->name }}</option>@endforeach</select></div><div class="sm:col-span-2"><label class="block text-sm font-bold">Description</label><textarea name="description" rows="3" class="mt-1 w-full rounded-md border-gray-300">{{ old('description', $mockTest->description) }}</textarea></div></div></section>
        <section class="rounded-lg border bg-white p-6 shadow-sm"><h3 class="font-bold">Test rules</h3><div class="mt-4 grid gap-4 sm:grid-cols-4"><div x-show="type==='theory'"><label class="text-sm font-bold">Questions</label><input type="number" name="question_count" value="{{ old('question_count', $mockTest->question_count) }}" class="mt-1 w-full rounded-md border-gray-300"></div><div x-show="type==='theory'"><label class="text-sm font-bold">Video questions last</label><input type="number" name="video_question_count" value="{{ old('video_question_count', $mockTest->video_question_count) }}" class="mt-1 w-full rounded-md border-gray-300"></div><div><label class="text-sm font-bold">Minutes</label><input type="number" name="duration_minutes" value="{{ old('duration_minutes', $mockTest->duration_minutes) }}" required class="mt-1 w-full rounded-md border-gray-300"></div><div><label class="text-sm font-bold">Pass mark</label><input type="number" name="pass_mark" value="{{ old('pass_mark', $mockTest->pass_mark) }}" required class="mt-1 w-full rounded-md border-gray-300"></div></div></section>
        <section x-show="type==='theory'" class="rounded-lg border bg-white p-6 shadow-sm"><h3 class="font-bold">Question pool</h3><p class="mb-3 text-sm text-gray-500">Leave all unchecked to use every topic. Questions and answer positions are randomized for each attempt.</p><div class="grid max-h-72 gap-2 overflow-y-auto sm:grid-cols-2">@foreach($topics as $topic)<label class="flex gap-2 rounded border p-3"><input type="checkbox" name="topic_ids[]" value="{{ $topic->id }}" @checked(in_array($topic->id, old('topic_ids', $mockTest->topics->pluck('id')->all())))><span>{{ $topic->name_en }}</span></label>@endforeach</div></section>
        <label class="flex items-center gap-2"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $mockTest->is_active))><span class="font-bold">Active and visible</span></label>
        <div class="flex gap-3"><button class="rounded-lg bg-primary px-6 py-3 font-bold text-white">{{ $editing ? 'Save changes' : 'Create mock test' }}</button><a href="{{ route('admin.mock-tests.index') }}" class="rounded-lg border px-6 py-3 font-bold">Cancel</a></div>
    </form>
</x-layouts.admin>
